import { StyleSheet } from 'react-native';
import { Colors } from '../theme/colors';

export const dashboardStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  list: { paddingHorizontal: 20, paddingBottom: 16 },
  top: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 8,
  },
  brand: { flexDirection: 'row', gap: 9, alignItems: 'center' },
  brandMark: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: Colors.mint,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandName: {
    fontSize: 25,
    fontWeight: '600',
    color: Colors.textPrimary,
    letterSpacing: -1,
  },
  iconButton: {
    width: 48,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  intro: { paddingTop: 16, paddingBottom: 12 },
  eyebrow: {
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 1.6,
    color: Colors.textSecondary,
  },
  title: {
    fontFamily: 'serif',
    fontSize: 30,
    color: Colors.textPrimary,
    marginTop: 7,
    letterSpacing: -0.5,
  },
  dateHeader: { flexDirection: 'row', alignItems: 'center' },
  dateLabel: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minHeight: 48,
  },
  month: {
    color: Colors.textPrimary,
    fontWeight: '600',
    fontSize: 14,
    flexShrink: 1,
  },
  todayButton: {
    minHeight: 48,
    paddingHorizontal: 8,
    justifyContent: 'center',
  },
  link: { color: Colors.accent, fontWeight: '600', fontSize: 14 },
  days: { flexGrow: 1, justifyContent: 'space-between', paddingBottom: 15 },
  dayCell: {
    minWidth: 48,
    flex: 1,
    alignItems: 'center',
    gap: 6,
    paddingVertical: 4,
  },
  weekday: { fontSize: 12, color: Colors.textSecondary },
  activeLabel: { color: Colors.accent, fontWeight: '700' },
  dayCircle: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EBEDE6',
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  dayCircleActive: { borderColor: Colors.accent, backgroundColor: '#E3EFE6' },
  dayNumber: { color: Colors.textPrimary, fontSize: 16 },
  dayNumberActive: { color: Colors.accent, fontWeight: '700' },
  future: { color: '#969F95' },
  dot: { width: 4, height: 4, borderRadius: 2, backgroundColor: 'transparent' },
  dotActive: { backgroundColor: Colors.coral },
  dotRecorded: { backgroundColor: '#95ADA0' },
  barActive: { backgroundColor: Colors.accent },
  barMuted: { backgroundColor: '#D6E4D9' },
  summary: {
    padding: 18,
    backgroundColor: Colors.card,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#EBECE5',
  },
  rowBetween: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  meta: { fontSize: 13, color: Colors.textSecondary },
  count: { fontSize: 11, color: Colors.textSecondary },
  total: {
    fontSize: 39,
    color: Colors.textPrimary,
    fontWeight: '500',
    letterSpacing: -1.7,
    marginTop: 10,
    marginBottom: 14,
    fontVariant: ['tabular-nums'],
  },
  summaryDivider: { height: 1, backgroundColor: '#F0F0EB', marginBottom: 14 },
  smallHeading: { fontSize: 14, color: Colors.textPrimary, fontWeight: '600' },
  weekTotal: { fontSize: 13, color: Colors.accent, fontWeight: '600' },
  chart: { flexGrow: 1, justifyContent: 'space-between', paddingTop: 12 },
  barColumn: { minWidth: 48, flex: 1, alignItems: 'center' },
  barValue: { fontSize: 9, color: Colors.textSecondary, marginBottom: 5 },
  barTrack: { height: 56, justifyContent: 'flex-end' },
  bar: { width: 18, borderRadius: 5 },
  chartLabel: { fontSize: 10, color: Colors.textSecondary, marginTop: 8 },
  listHeading: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 8,
    paddingTop: 24,
    paddingBottom: 16,
  },
  sectionTitle: {
    fontFamily: 'serif',
    fontSize: 27,
    color: Colors.textPrimary,
    flexShrink: 1,
  },
  expenseCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: Colors.card,
    borderRadius: 18,
    padding: 15,
    marginBottom: 11,
    elevation: 1,
    shadowColor: '#243A29',
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
  },
  categoryIcon: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
  },
  expenseBody: { flex: 1, gap: 6 },
  expenseMain: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: 10,
    rowGap: 3,
    justifyContent: 'space-between',
  },
  expenseCategory: {
    fontSize: 15,
    fontWeight: '600',
    color: Colors.textPrimary,
    flexShrink: 1,
  },
  expenseAmount: {
    fontSize: 15,
    fontWeight: '600',
    color: Colors.textPrimary,
    fontVariant: ['tabular-nums'],
  },
  expenseMeta: { fontSize: 11, lineHeight: 16, color: Colors.textSecondary },
  notice: {
    padding: 12,
    backgroundColor: '#EFEFE7',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  noticeText: { flex: 1, fontSize: 13, color: Colors.textSecondary },
  retry: {
    minHeight: 48,
    minWidth: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  empty: {
    alignItems: 'center',
    padding: 24,
    backgroundColor: Colors.card,
    borderRadius: 18,
    gap: 10,
  },
  emptyIcon: { backgroundColor: Colors.mint, padding: 16, borderRadius: 36 },
  emptyTitle: {
    fontFamily: 'serif',
    fontSize: 21,
    color: Colors.textPrimary,
    textAlign: 'center',
  },
  emptyText: {
    fontSize: 13,
    color: Colors.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
  },
  footerNote: {
    fontSize: 11,
    textAlign: 'center',
    color: Colors.textSecondary,
    marginVertical: 18,
  },
  navigation: {
    backgroundColor: Colors.card,
    borderTopWidth: 1,
    borderColor: '#E9ECE5',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 12,
  },
  navItem: {
    minWidth: 64,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  navLabel: { fontSize: 11, color: Colors.textSecondary, fontWeight: '500' },
  navActive: { color: Colors.coral },
  voiceButton: {
    minHeight: 48,
    borderRadius: 26,
    backgroundColor: Colors.accent,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    flexShrink: 1,
  },
  voiceButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 13,
    flexShrink: 1,
  },
  homeIntro: {
    color: Colors.textSecondary,
    fontSize: 15,
    lineHeight: 23,
    marginBottom: 24,
  },
  deviceCard: {
    padding: 24,
    backgroundColor: Colors.card,
    borderRadius: 22,
    marginBottom: 16,
  },
  deviceIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: Colors.mint,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  deviceBadge: {
    fontSize: 10,
    letterSpacing: 1.4,
    fontWeight: '600',
    color: Colors.accent,
    marginBottom: 8,
  },
  deviceName: {
    fontSize: 25,
    fontFamily: 'serif',
    color: Colors.textPrimary,
    marginBottom: 6,
  },
  deviceMeta: { fontSize: 13, color: Colors.textSecondary, marginBottom: 12 },
  deviceDescription: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.textSecondary,
  },
  homeVoice: {
    padding: 16,
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  homeVoiceText: { flex: 1, color: Colors.textSecondary, lineHeight: 21 },
  voiceArt: {
    alignSelf: 'center',
    padding: 30,
    borderRadius: 60,
    backgroundColor: Colors.mint,
    marginVertical: 12,
  },
  voicePrompt: {
    color: Colors.textPrimary,
    fontSize: 23,
    fontFamily: 'serif',
    textAlign: 'center',
    lineHeight: 32,
  },
  voiceHint: {
    fontSize: 14,
    color: Colors.textSecondary,
    lineHeight: 22,
    textAlign: 'center',
  },
  primaryButton: {
    minHeight: 56,
    borderRadius: 28,
    backgroundColor: Colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  primaryText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 16,
    textAlign: 'center',
  },
  settingButton: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  notes: {
    minHeight: 100,
    backgroundColor: Colors.background,
    padding: 16,
    borderRadius: 12,
    color: Colors.textPrimary,
    textAlignVertical: 'top',
  },
});
